### ISSUE TITLE
Messages don't send/No noise

### ISSUE THREAD

**Issue by VerseOW** [Chatterino/chatterino-browser-ext#58] opened 2021-04-26 14:55 UTC
I recently got chaterino and it was fine but now I'm not able to send messages when I'm on chatterino. It's not a Twitch issue with a fast chat, I tried sending messages in a chat with 0 viewers, still doesn't work

Unrelated to that issue, I also had an issue before that one which made it so I wasn't able to hear the noise for when I get pinged

**Comment by VerseOW** [comment] 2021-04-26 15:28
Sending messages seems to have randomly started to work again, still don't hear the noise for pings though

**Comment by alazymeme** [comment] 2021-05-02 23:20
A few things here:
- Please don't open 1 issue with multiple issues contained within it, it should be strictly 1 issue per report
- This is a duplicate of https://github.com/Chatterino/chatterino2/issues/1228

**Comment by zneix** [comment] 2021-05-02 23:23
Duplicate of #1228, other things such as not sending message may have been temporary, completely unrelated to the issue.

**Closed by zneix** 2021-05-02 23:23 UTC
