### ISSUE TITLE
native chatterino crashing

### ISSUE THREAD

**Issue by madstingray16** [Chatterino/chatterino-browser-ext#53] opened 2021-04-17 23:54 UTC
idk what the format is but here is the issue, chatterino crashes instantly when the native chat loads. I've heard that this next issue is because of native chat, crashes occur when changing tab and tabbing in and out while native is up on twitch. (the first bug is a new issues from the 2.3.0 update and the second one has been happening for a long time)

**Comment by Felanbird** [comment] 2021-05-04 02:04
@madstingray16 can you try 2.3.1 that was released today

**Comment by caneleex** [comment] 2021-05-14 19:21
> 
> 
> @madstingray16 can you try 2.3.1 that was released today
> 
> (toggle "receive beta updates" on)
> 
> ![image](https://user-images.githubusercontent.com/41973452/116954113-12116d00-ac5d-11eb-9476-96807117949f.png)

i can still repro this on 2.3.1

**Comment by Felanbird** [comment] 2021-05-17 05:42
> > @madstingray16 can you try 2.3.1 that was released today
> > (toggle "receive beta updates" on)
> > ![image](https://user-images.githubusercontent.com/41973452/116954113-12116d00-ac5d-11eb-9476-96807117949f.png)
> 
> i can still repro this on 2.3.1, see [this](https://github.com/Chatterino/chatterino2/issues/2704#issuecomment-839713170)

can you try 2.3.2 now, sadly without a crash log we can't be 100% sure but see https://github.com/Chatterino/chatterino2/issues/2774

**Comment by caneleex** [comment] 2021-05-17 11:28
it seems to be better on the latest nightly build, will see if the issue comes back

**Comment by caneleex** [comment] 2021-05-17 20:31
@Felanbird the freezing or crashing at startup seems to be fixed now, though chatterino still crashes when i switch away from a stream. i've already tried to get logs, but there were no crash logs generated so yeah

**Comment by ALazyMeme** [comment] 2021-07-25 11:42
Cannot reproduce, Chatterino 2.3.3 (commit c8c28d7f5)
Microsoft Edge Version 92.0.902.55

**Comment by caneleex** [comment] 2021-07-25 11:55
I still can repro this issue, running Chatterino 2.3.3 commit b352dea2d and Firefox 90.0.2

**Comment by ALazyMeme** [comment] 2021-07-25 11:58
This issue actually refers to 2 issues in itself. One of them is resolved, I think the other should be ported to it's own issue as not to cause confusion.

**Closed** 2021-07-26 08:55 UTC
