### ISSUE TITLE
Is browser integration still not supported on Opera gx?

### ISSUE THREAD

**Issue by Chilli-x** [Chatterino/chatterino-browser-ext#63] opened 2021-07-25 07:49 UTC
i can't seem to get it to work but the last time someone asked was like a year ago, so am i doing something wrong or is it just not supported?

**Comment by ALazyMeme** [comment] 2021-07-25 10:46
Duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/43

**Closed** 2021-07-25 12:04 UTC
