### ISSUE TITLE
Chatterino keeps crashing

### ISSUE THREAD

**Issue by juancalcetin** [Chatterino/chatterino-browser-ext#56] opened 2021-04-22 23:51 UTC
After new update 2.3.0, Chatterino keeps crashing when trying to load chat on web extension, using Firefox.

**Comment by Felanbird** [comment] 2021-05-04 02:04
@juancalcetin can you try 2.3.1 that was released today

**Comment by ALazyMeme** [comment] 2021-07-25 11:42
Cannot reproduce, Chatterino 2.3.3 (commit c8c28d7f5)
Microsoft Edge Version 92.0.902.55

**Comment by ALazyMeme** [comment] 2021-07-25 11:59
Also duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/56

**Closed** 2021-07-25 12:05 UTC
