### ISSUE TITLE
use channel points with extension

### ISSUE THREAD

**Issue by jeovanny315** [Chatterino/chatterino-browser-ext#52] opened 2021-02-19 08:12 UTC
sorry if this is the wrong the place, i couldn't figure out how to do pull request. I want to use the extension and channel points at the same time. is this possible????

**Comment by leon-richardt** [comment] 2021-02-19 08:28
Basically a duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/51. :smile: To my knowledge, it is currently not possible.

**Comment by zneix** [comment] 2021-04-25 20:37
Duplicate of #51

**Closed by zneix** 2021-04-25 20:37 UTC
