### ISSUE TITLE
Opera GX does not seem to be compatible with Chatterino

### ISSUE THREAD

**Issue by HypoCheese** [Chatterino/chatterino-browser-ext#44] opened 2020-10-28 12:31 UTC
The browser is quite comfortable, and the move from Chrome was real easy (Chrome had far too many memory and CPU-consuming issues for me to even bother staying with it). However, my beloved Chatterino no longer works!

**Comment by alazymeme** [comment] 2020-10-28 12:33
Duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/43

**Comment by cinemassacres** [comment] 2020-11-18 04:21
should close this

**Closed** 2020-11-21 11:36 UTC
