### ISSUE TITLE
Watching tab.

### ISSUE THREAD

**Issue by StephanBruh** [Chatterino/chatterino-browser-ext#42] opened 2020-10-03 09:26 UTC
Right now you have only 1 choice, enable it and attach chatterino to your browser and add use the watching tab. But not a option where you can only have the "Watching" tab working. Unticking the box Replace chat in the extension setting would disable the complete extension and you "Watching" tab wont work anymore.

**Comment by alazymeme** [comment] 2020-10-03 12:18
Duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/30

**Closed** 2020-10-24 14:37 UTC
